#include "security.h"
#include "judge.h"

//此表存放系统调用允许调用次数
short int syscall_enable[1024];

//C和C++程序允许调用的系统调用表，execve调用另外处理
//下表的调用不限次数
int syscall_enable_c_cpp[25]=
{
	SYS_access,
	SYS_brk,
	SYS_mmap,
	SYS_mmap2,
	SYS_fstat64,
	SYS_stat64,
	SYS_open,
	SYS_close,
	SYS_read,
	SYS_set_thread_area,
	SYS_mprotect,
	SYS_munmap,
	SYS_write,
	SYS_writev,
	SYS_exit_group,
	SYS_uname,
	SYS_splice,
	SYS_ugetrlimit,
	SYS_readlink,
	SYS_clone,
	SYS_exit,
	SYS_getuid32,
	SYS_getgid32,
	SYS_geteuid32,
	SYS_getegid32
};




//JVM虚拟机允许调用的系统调用表
//此调用列表来源于武汉大学WOJ开源项目
int syscall_enable_java[34]=
{
    SYS_execve,
    SYS_ugetrlimit,
    SYS_futex,     
    SYS_read,      
    SYS_mmap,      
    SYS_mmap2,     
    SYS_stat64,    
    SYS_open,      
    SYS_close,     
    SYS_access,    
    SYS_brk,       
    SYS_readlink, 
    SYS_munmap,    
    SYS_close,     
    SYS_uname,     
    SYS_clone,     
    SYS_rt_sigprocmask,
    SYS_rt_sigaction,
    SYS_sigprocmask,
    SYS_getrlimit, 
    SYS_fstat64,   
    SYS_getuid32,  
    SYS_getgid32,  
    SYS_geteuid32, 
    SYS_getegid32, 
    SYS_set_thread_area,
    SYS_set_tid_address,
    SYS_set_robust_list,
    SYS_exit_group,
    SYS_exit,      
    SYS_mprotect,  
    SYS_getdents64,
    SYS_fcntl64,
    SYS_writev
};




//初始化系统允许调用的系统调用表
void init_syscall_enable(int lang){

	//处理C和C++语言程序的调用列表
	if(lang==LANG_GCC||lang==LANG_GPP){

		//将全部系统调用设为禁止，再想其中添加可以调用的系统调用，并进行限制
		memset(syscall_enable,0,sizeof(syscall_enable));
		//execve在fork后，必然要调用一次替换当前进程数据为用户提交代码编译出的程序
		//本调用只能调用一次
		syscall_enable[SYS_execve]=1;  
		

		int i;
		for(i=0;i<25;i++)
			//如果syscall_enable的元素值为负数，则此调用不限调用次数，为0则禁止调用
			//正数则指定该调用最多能调用多少次
			syscall_enable[syscall_enable_c_cpp[i]]=-1;
	}

	//处理JAVA语言的调用列表，本质上是对JVM能调用的系统调用进行限制
	else if(lang==LANG_JAVA){
		memset(syscall_enable,0,sizeof(syscall_enable));
		int j;
		for(j=0;j<34;j++)
			syscall_enable[syscall_enable_java[j]]=-1;
	}
}

	
int is_enable_syscall(int syscall_id){

	//对不限制调用次数的系统调用，直接返回1
	if(syscall_enable[syscall_id]==-1)
		return 1;
	else if(syscall_enable[syscall_id]>0){
	//限制了调用次数的系统调用，则将其调用次数减1，返回1
		syscall_enable[syscall_id]--;
		return 1;
	}
	else
	//对于不允许的系统调用，直接返回0
		return 0;
}

/*系统调用列表*/
table syscall_table[] = {
	{"restart_syscall", 0, NULL },
	{"exit", 1, NULL },
	{"fork", 0, NULL },
	{"read", 1, /*process_read*/NULL },
	{"write", 1, /*process_write*/NULL },
	{"open", 1, /*process_open*/NULL },
	{"close", 1, /*process_close*/NULL },
	{"waitpid", 0, NULL },
	{"creat", 0, NULL },
	{"link", 0, NULL },
	{"unlink", 1,NULL},
	{"execve", 1, NULL },
	{"chdir", 0, NULL },
	{"time", 1, NULL },
	{"mknod", 0, NULL },
	{"chmod", 0, NULL },
	{"lchown", 0, NULL },
	{"break", 0, NULL },
	{"oldstat", 0, NULL },
	{"lseek", 0, NULL },
	{"getpid", 0, NULL },
	{"mount", 0, NULL },
	{"umount", 0, NULL },
	{"setuid", 0, NULL },
	{"getuid", 0, NULL },
	{"stime", 0, NULL },
	{"ptrace", 0, NULL },
	{"alarm", 0, NULL },
	{"oldfstat", 0, NULL },
	{"pause", 0, NULL },
	{"utime", 0, NULL },
	{"stty", 0, NULL },
	{"gtty", 0, NULL },
	{"access", 1, NULL },
	{"nice", 0, NULL },
	{"ftime", 0, NULL },
	{"sync", 0, NULL },
	{"kill", 0, NULL },
	{"rename", 0, NULL },
	{"mkdir", 0, NULL },
	{"rmdir", 0, NULL },
	{"dup", 0, NULL },
	{"pipe", 0, NULL },
	{"times", 1, NULL },
	{"prof", 0, NULL },
	{"brk", 2, NULL },
	{"setgid", 0, NULL },
	{"getgid", 0, NULL },
	{"signal", 0, NULL },
	{"geteuid", 0, NULL },
	{"getegid", 0, NULL },
	{"acct", 0, NULL },
	{"umount2", 0, NULL },
	{"lock", 0, NULL },
	{"ioctl", 0, NULL },
	{"fcntl", 0, NULL },
	{"mpx", 0, NULL },
	{"setpgid", 0, NULL },
	{"ulimit", 0, NULL },
	{"oldolduname", 0, NULL },
	{"umask", 0, NULL },
	{"chroot", 0, NULL },
	{"ustat", 0, NULL },
	{"dup2", 0, NULL },
	{"getppid", 0, NULL },
	{"getpgrp", 0, NULL },
	{"setsid", 0, NULL },
	{"sigaction", 0, NULL },
	{"sgetmask", 0, NULL },
	{"ssetmask", 0, NULL },
	{"setreuid", 0, NULL },
	{"setregid", 0, NULL },
	{"sigsuspend", 0, NULL },
	{"sigpending", 0, NULL },
	{"sethostname", 0, NULL },
	{"setrlimit", 0, NULL },
	{"getrlimit", 0, NULL },
	{"getrusage", 0, NULL },
	{"gettimeofday", 0, NULL },
	{"settimeofday", 0, NULL },
	{"getgroups", 0, NULL },
	{"setgroups", 0, NULL },
	{"select", 0, NULL },
	{"symlink", 0, NULL },
	{"oldlstat", 0, NULL },
	{"readlink", 1, NULL },
	{"uselib", 0, NULL },
	{"swapon", 0, NULL },
	{"reboot", 0, NULL },
	{"readdir", 0, NULL },
	{"mmap", 2, /*process_mmap*/NULL },
	{"munmap", 2, NULL },
	{"truncate", 0, NULL },
	{"ftruncate", 0, NULL },
	{"fchmod", 0, NULL },
	{"fchown", 0, NULL },
	{"getpriority", 0, NULL },
	{"setpriority", 0, NULL },
	{"profil", 0, NULL },
	{"statfs", 0, NULL },
	{"fstatfs", 0, NULL },
	{"ioperm", 0, NULL },
	{"socketcall", 0, NULL },
	{"syslog", 0, NULL },
	{"setitimer", 0, NULL },
	{"getitimer", 0, NULL },
	{"stat", 0, NULL },
	{"lstat", 0, NULL },
	{"fstat", 0, NULL },
	{"olduname", 0, NULL },
	{"iopl", 0, NULL },
	{"vhangup", 0, NULL },
	{"idle", 0, NULL },
	{"vm86old", 0, NULL },
	{"wait4", 0, NULL },
	{"swapoff", 0, NULL },
	{"sysinfo", 0, NULL },
	{"ipc", 0, NULL },
	{"fsync", 0, NULL },
	{"sigreturn", 0, NULL },
	{"clone", 2, NULL },
	{"setdomainname", 0, NULL },
	{"uname", 1, NULL/*process_uname*/ },
	{"modify_ldt", 0, NULL },
	{"adjtimex", 0, NULL },
	{"mprotect", 2, NULL },
	{"sigprocmask", 0, NULL },
	{"create_module", 0, NULL },
	{"init_module", 0, NULL },
	{"delete_module", 0, NULL },
	{"get_kernel_syms", 0, NULL },
	{"quotactl", 0, NULL },
	{"getpgid", 0, NULL },
	{"fchdir", 0, NULL },
	{"bdflush", 0, NULL },
	{"sysfs", 0, NULL },
	{"personality", 0, NULL },
	{"afs_syscall", 0, NULL },
	{"setfsuid", 0, NULL },
	{"setfsgid", 0, NULL },
	{"_llseek", 1, NULL },
	{"getdents", 0, NULL },
	{"_newselect", 0, NULL },
	{"flock", 0, NULL },
	{"msync", 0, NULL },
	{"readv", 0, NULL },
	{"writev", 1, NULL },
	{"getsid", 0, NULL },
	{"fdatasync", 0, NULL },
	{"_sysctl", 0, NULL },
	{"mlock", 0, NULL },
	{"munlock", 0, NULL },
	{"mlockall", 0, NULL },
	{"munlockall", 0, NULL },
	{"sched_setparam", 0, NULL },
	{"sched_getparam", 0, NULL },
	{"sched_setscheduler", 0, NULL },
	{"sched_getscheduler", 0, NULL },
	{"sched_yield", 0, NULL },
	{"sched_get_priority_max", 0, NULL },
	{"sched_get_priority_min", 0, NULL },
	{"sched_rr_get_interval", 0, NULL },
	{"nanosleep", 0, NULL },
	{"mremap", 0, NULL },
	{"setresuid", 0, NULL },
	{"getresuid", 0, NULL },
	{"vm86", 0, NULL },
	{"query_module", 0, NULL },
	{"poll", 0, NULL },
	{"nfsservctl", 0, NULL },
	{"setresgid", 0, NULL },
	{"getresgid", 0, NULL },
	{"prctl", 0, NULL },
	{"rt_sigreturn", 0, NULL },
	{"rt_sigaction", 1, NULL/*process_rt_sigaction*/ },
	{"rt_sigprocmask", 1, NULL/*process_rt_sigprocmask*/ },
	{"rt_sigpending", 0, NULL },
	{"rt_sigtimedwait", 0, NULL },
	{"rt_sigqueueinfo", 0, NULL },
	{"rt_sigsuspend", 0, NULL },
	{"pread64", 0, NULL },
	{"pwrite64", 0, NULL },
	{"chown", 0, NULL },
	{"getcwd", 0, NULL },
	{"capget", 0, NULL },
	{"capset", 0, NULL },
	{"sigaltstack", 0, NULL },
	{"sendfile", 0, NULL },
	{"getpmsg", 0, NULL },
	{"putpmsg", 0, NULL },
	{"vfork", 0, NULL },
	{"ugetrlimit", 1, NULL },
	{"mmap2", 2, /*process_mmap*/NULL },
	{"truncate64", 0, NULL },
	{"ftruncate64", 0, NULL },
	{"stat64", 1, NULL },
	{"lstat64", 0, NULL },
	{"fstat64", 1, NULL },
	{"lchown32", 0, NULL },
	{"getuid32", 1, NULL },
	{"getgid32", 1, NULL },
	{"geteuid32", 1, NULL },
	{"getegid32", 1, NULL },
	{"setreuid32", 0, NULL },
	{"setregid32", 0, NULL },
	{"getgroups32", 0, NULL },
	{"setgroups32", 0, NULL },
	{"fchown32", 0, NULL },
	{"setresuid32", 0, NULL },
	{"getresuid32", 0, NULL },
	{"setresgid32", 0, NULL },
	{"getresgid32", 0, NULL },
	{"chown32", 0, NULL },
	{"setuid32", 0, NULL },
	{"setgid32", 0, NULL },
	{"setfsuid32", 0, NULL },
	{"setfsgid32", 0, NULL },
	{"pivot_root", 0, NULL },
	{"mincore", 0, NULL },
	{"madvise", 0, NULL },
	{"getdents64", 0, NULL },
	{"fcntl64", 0, NULL },
	{"gettid", 0, NULL },
	{"readahead", 0, NULL },
	{"setxattr", 0, NULL },
	{"lsetxattr", 0, NULL },
	{"fsetxattr", 0, NULL },
	{"getxattr", 0, NULL },
	{"lgetxattr", 0, NULL },
	{"fgetxattr", 0, NULL },
	{"listxattr", 0, NULL },
	{"llistxattr", 0, NULL },
	{"flistxattr", 0, NULL },
	{"removexattr", 0, NULL },
	{"lremovexattr", 0, NULL },
	{"fremovexattr", 0, NULL },
	{"tkill", 0, NULL },
	{"sendfile64", 0, NULL },
	{"futex", 0, NULL },
	{"sched_setaffinity", 0, NULL },
	{"sched_getaffinity", 1, NULL },
	{"set_thread_area", 0, NULL },
	{"get_thread_area", 0, NULL },
	{"io_setup", 2, NULL },
	{"io_destroy", 0, NULL },
	{"io_getevents", 0, NULL },
	{"io_submit", 0, NULL },
	{"io_cancel", 0, NULL },
	{"fadvise64", 0, NULL },
	{"(null)", 0, NULL },
	{"exit_group", 0, NULL },
	{"lookup_dcookie", 0, NULL },
	{"epoll_create", 1, /*process_epoll_create*/NULL },
	{"epoll_ctl", 0, NULL },
	{"epoll_wait", 0, NULL },
	{"remap_file_pages", 0, NULL },
	{"set_tid_address", 0, NULL },
	{"timer_create", 0, NULL },
	{"timer_settime", 1, NULL },
	{"timer_gettime", 0, NULL },
	{"timer_getoverrun", 0, NULL },
	{"timer_delete", 0, NULL },
	{"clock_settime", 0, NULL },
	{"clock_gettime", 0, NULL },
	{"clock_getres", 0, NULL },
	{"clock_nanosleep", 0, NULL },
	{"statfs64", 0, NULL },
	{"fstatfs64", 0, NULL },
	{"tgkill", 0, NULL },
	{"utimes", 0, NULL },
	{"fadvise64_64", 1, NULL },
	{"vserver", 0, NULL },
	{"mbind", 0, NULL },
	{"get_mempolicy", 0, NULL },
	{"set_mempolicy", 0, NULL },
	{"mq_open", 0, NULL },
	{"mq_unlink", 0, NULL },
	{"mq_timedsend", 0, NULL },
	{"mq_timedreceive", 0, NULL },
	{"mq_notify", 0, NULL },
	{"mq_getsetattr", 0, NULL },
	{"kexec_load", 0, NULL },
	{"waitid", 0, NULL },
	{"(null)", 0, NULL },
	{"add_key", 0, NULL },
	{"request_key", 0, NULL },
	{"keyctl", 0, NULL },
	{"ioprio_set", 0, NULL },
	{"ioprio_get", 0, NULL },
	{"inotify_init", 0, NULL },
	{"inotify_add_watch", 0, NULL },
	{"inotify_rm_watch", 0, NULL },
	{"migrate_pages", 0, NULL },
	{"openat", 0, NULL },
	{"mkdirat", 0, NULL },
	{"mknodat", 0, NULL },
	{"fchownat", 0, NULL },
	{"futimesat", 0, NULL },
	{"fstatat64", 0, NULL },
	{"unlinkat", 0, NULL },
	{"renameat", 0, NULL },
	{"linkat", 0, NULL },
	{"symlinkat", 0, NULL },
	{"readlinkat", 0, NULL },
	{"fchmodat", 0, NULL },
	{"faccessat", 0, NULL },
	{"pselect6", 0, NULL },
	{"ppoll", 0, NULL },
	{"unshare", 0, NULL },
	{"set_robust_list", 0, NULL },
	{"get_robust_list", 0, NULL },
	{"splice", 1, NULL },
	{"sync_file_range", 0, NULL },
	{"tee", 0, NULL },
	{"vmsplice", 0, NULL },
	{"move_pages", 0, NULL },
	{"getcpu", 0, NULL },
	{"epoll_pwait", 0, NULL },
	{"utimensat", 0, NULL },
	{"signalfd", 0, NULL },
	{"timerfd_create", 0, NULL },
	{"eventfd", 0, NULL },
	{"fallocate", 0, NULL },
	{"timerfd_settime", 0, NULL },
	{"timerfd_gettime", 0, NULL },
	{"signalfd4", 0, NULL },
	{"eventfd2", 0, NULL },
	{"epoll_create1", 0, NULL },
	{"dup3", 0, NULL },
	{"pipe2", 0, NULL },
	{"inotify_init1", 0, NULL },
	{"preadv", 0, NULL },
	{"pwritev", 0, NULL },
	{"rt_tgsigqueueinfo", 0, NULL },
	{"perf_counter_open", 0, NULL}
};

